# Generated by Django 5.1.4 on 2025-01-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_visitedcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='visitedcities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.city'),
        ),
    ]
