# Generated by Django 5.1.4 on 2025-01-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_city_alter_visitedcities_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=168),
        ),
    ]
