# Generated by Django 5.1.4 on 2025-01-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_city_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedcities',
            old_name='country',
            new_name='city',
        ),
    ]
