# Generated by Django 5.1.4 on 2025-01-31 16:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_rename_country_visitedcities_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.RemoveField(
            model_name='visitedcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visitedcountry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='VisitedCountry',
        ),
    ]
