# Generated by Django 5.1.4 on 2025-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_alter_city_country_remove_visitedcountry_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='elevation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='geonameid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='modification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
